spring:
  application:
    name: backend

  datasource:
    url: ${db-url}
    username: ${db-user}
    password: ${db-password}

  jpa:
    hibernate:
      ddl-auto: validate

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} %-5level %logger{36} - %msg%n"
  level:
    root: debug
    com.bhnatiuk.uni.bookstore: debug